---
name: Deploy

on:
  - push

env:
  APP_NAME: timestampcollectorprod

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install dependencies
        run: |
          npm i -g azure-functions-core-tools@3 --unsafe-perm true \
          && npm install
      - name: Deploy
        run: npm run deploy $APP_NAME
