---
name: Deploy

on:
  - push

env:
  APP_NAME: timestampcollectorprod
  FUNCTIONS_WORKER_RUNTIME": "node"

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Install dependencies
        run: |
          npm i -g azure-functions-core-tools@3 --unsafe-perm true \
          && npm install
      - name: Deploy
        run: npm run deploy $APP_NAME
