---
name: Lint Test

on:
  - push

jobs:
  lint-test:
    runs-on: ubuntu-latest
    container: docker.pkg.github.com/timestamp-app/build-image/node:latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm test
