name: Lint Test Deploy

on:
  - push

env:
  AZURE_FUNCTIONAPP_NAME: devduck
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'

jobs:
  lint-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r __app__/requirements.txt
          pip install -r requirements.txt
      - name: Lint
        run: make lint
      - name: Test
        run: make test
      - name: Deploy
        uses: Azure/functions-action@v1
        if: ${{ github.ref == 'refs/heads/dev' }}
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.DEV_PUBLISH_PROFILE }}
      - name: Int test
        if: ${{ github.ref == 'refs/heads/dev' }}
        env:
          FUNCTION_KEY: ${{ secrets.DEV_FUNCTION_KEY }}
        run: make int_test
