---

name: Lint Test

on:
  - push

env:
  FUNCTION_KEY: ${{ secrets.DEV_FUNCTION_KEY }}

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm test
