---
name: Lint Test

on:
  - push

jobs:
  lint-test:
    runs-on: ubuntu-latest
    container:
      image: docker.pkg.github.com/timestamp-app/build-image/node:latest
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint:report
      - name: Test
        run: npm run test
      - name: SonarCloud Scan
        run: npm run sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
